### ISSUE TITLE
хочу замовити парсер

### ISSUE THREAD

**Issue by den-ga-px** [kyryliuk/CopartParser#3]
Привіт, можемо сконтактуватися в телеграмі / деінде?

**Comment by TRIP-TANK** [comment]
Так, звісно. https://t.me/SHADOWMACHINE

вс, 24 янв. 2021 г., 18:12 den-ga-px <notifications@github.com>:

**Comment by den-ga-px** [comment]
Юзер взяв за парсер 300 долларів і зник. Фрод.

**Comment by kyryliuk** [comment]
@den-ga-px Шкода це чути.

**Comment by den-ga-px** [comment]
@kyryliuk/CopartParser ***@***.***> , я так розумію,
ти повертати кошти не збираєшся?

чт, 11 нояб. 2021 г. в 11:29, Roman ***@***.***>:

**Comment by kyryliuk** [comment]
@den-ga-px Звичайно ж що ні, це ж не я їх брав в тебе.

**Comment by den-ga-px** [comment]
@kyryliuk/CopartParser ***@***.***> , контакт ти
висилав?

чт, 11 нояб. 2021 г. в 12:33, Roman ***@***.***>:

**Comment by kyryliuk** [comment]
@den-ga-px Ні, він сам тут написав. Тут може будь хто залишати коментарі.

**Comment by den-ga-px** [comment]
Можеш відновити його контакти\нікнейм тут?

**Comment by den-ga-px** [comment]
@kyryliuk ^

**Comment by kyryliuk** [comment]
@den-ga-px Я його видалив, шоб більше ніхто не натрапляв, вот хіба його юзер , комент його відновити не можу https://github.com/TRIP-TANK
